import Link from "next/link";
import { auth } from "@clerk/nextjs/server";
import { Button } from "@/components/ui/button";
import {FileText,Brain,MessageSquare,Users,ArrowRight,ShieldCheck,History,Sparkles,Search,Download,Lock,UploadCloud,FileStack,} from "lucide-react";
import { prisma } from "@/lib/prisma";

const ACCENT = "text-blue-600 dark:text-blue-400";
const ACCENT_BG = "bg-blue-600/10";

export default async function Home() {
  let userId: string | null = null;
  let orgId: string | null = null;
  let organization: { slug: string } | null = null;

  try {
    const authData = await auth();
    userId = authData.userId;
    orgId = authData.orgId ?? null;

    if (orgId) {
      organization = await prisma.organization.findUnique({
        where: { clerkOrgId: orgId },
      });
    }
  } catch (error) {
    console.error("Home page error:", error);
  }

  const primaryHref = !userId
    ? "/sign-up"
    : orgId
    ? `/${organization?.slug}/documents`
    : "/select-org";

  const primaryLabel = !userId
    ? "Get started"
    : orgId
    ? "Go to documents"
    : "Select organization";

  return (
    <main>
      {/* Hero */}
      <section className="border-b overflow-hidden">
        <div className="container max-w-6xl mx-auto px-6 py-24 grid lg:grid-cols-[1.1fr_0.9fr] gap-16 items-center">
          <div>
            <div className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-sm mb-6 ${ACCENT_BG}`}>
              <span className={`h-1.5 w-1.5 rounded-full ${ACCENT} bg-current`} />
              Secure, multi-tenant document intelligence
            </div>

            <h1 className="text-5xl md:text-6xl font-bold tracking-tight leading-[1.05]">
              Every document your team uploads,
              <span className={ACCENT}> understood instantly.</span>
            </h1>

            <p className="mt-6 text-lg text-muted-foreground leading-8 max-w-xl">
              DocDocGo is a workspace for organizations to upload, analyze, and
              track contracts, reports, and notes. Summaries, keywords, and
              answers are generated by Gemini AI &mdash; with every version kept,
              every workspace isolated, and every request checked against who
              you are and what you belong to.
            </p>

            <div className="mt-8 flex flex-wrap gap-4">
              {!userId ? (
                <>
                  <Link href="/sign-up">
                    <Button size="lg">
                      Get Started
                      <ArrowRight className="ml-2 h-4 w-4" />
                    </Button>
                  </Link>
                  <Link href="/sign-in">
                    <Button size="lg" variant="outline">
                      Sign In
                    </Button>
                  </Link>
                </>
              ) : (
                <Link href={primaryHref}>
                  <Button size="lg">
                    {primaryLabel}
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>
                </Link>
              )}
            </div>

            <div className="mt-10 flex flex-wrap items-center gap-x-8 gap-y-2 text-sm text-muted-foreground">
              <span>PDF</span>
              <span className="opacity-30">/</span>
              <span>DOCX</span>
              <span className="opacity-30">/</span>
              <span>TXT</span>
              <span className="opacity-30">/</span>
              <span>Markdown</span>
            </div>
          </div>

          {/* Signature element: version stack */}
          <div className="relative h-[380px] hidden lg:block">
            <div className="absolute inset-0 flex items-center justify-center">
              {[
                { v: "v1", offset: "translate-x-[-56px] translate-y-10 rotate-[-9deg]", z: "z-10", faded: true },
                { v: "v2", offset: "translate-x-[-14px] translate-y-3 rotate-[-3deg]", z: "z-20", faded: true },
                { v: "v3", offset: "translate-x-8 -translate-y-6 rotate-[2deg]", z: "z-30", faded: false },
              ].map((card) => (
                <div
                  key={card.v}
                  className={`absolute w-64 rounded-xl border bg-background shadow-lg p-5 transition-transform ${card.offset} ${card.z} ${
                    card.faded ? "opacity-70" : ""
                  }`}
                >
                  <div className="flex items-center justify-between mb-4">
                    <FileText className="h-5 w-5 text-muted-foreground" />
                    <span
                      className={`font-mono text-xs rounded-full px-2 py-0.5 border ${
                        card.faded ? "text-muted-foreground" : `${ACCENT} border-current`
                      }`}
                    >
                      {card.v}
                      {card.v === "v3" ? " · latest" : ""}
                    </span>
                  </div>
                  <div className="h-2 rounded bg-muted w-4/5 mb-2" />
                  <div className="h-2 rounded bg-muted w-3/5 mb-2" />
                  <div className="h-2 rounded bg-muted w-2/3" />
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* What is DocDocGo */}
      <section className="py-20">
        <div className="container max-w-5xl mx-auto px-6">
          <h2 className="text-3xl font-bold mb-6">What is DocDocGo?</h2>
          <p className="text-lg text-muted-foreground leading-8">
            DocDocGo gives organizations a shared, permissioned workspace for
            their documents. Instead of reading a contract or report line by
            line, upload it and DocDocGo extracts the text, runs it through
            Gemini AI, and hands back a summary, sentiment, and keywords in
            seconds &mdash; while a full version history and role-based access
            keep every workspace's files separate and accounted for.
          </p>
        </div>
      </section>

      {/* Features */}
      <section className="bg-muted/40 py-20">
        <div className="container max-w-6xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-center mb-4">Features</h2>
          <p className="text-center text-muted-foreground mb-12 max-w-2xl mx-auto">
            Everything a team needs to upload, understand, and govern its
            documents in one place.
          </p>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            <FeatureCard
              icon={<UploadCloud className="h-7 w-7" />}
              title="Upload & organize documents"
              description="Upload PDF, DOCX, TXT, or Markdown files. Documents are stored securely in Vercel Blob Storage, with metadata such as file type, size, uploader, and upload date automatically recorded."
            />

            <FeatureCard
              icon={<Brain className="h-7 w-7" />}
              title="AI-powered document analysis"
              description="Analyze documents using Gemini AI to generate concise summaries, sentiment analysis, and keyword extraction, helping users quickly understand lengthy content."
            />

            <FeatureCard
              icon={<History className="h-7 w-7" />}
              title="Automatic version history"
              description="Uploading a document with the same name creates a new version instead of overwriting the original. Previous versions are preserved for reference and tracking."
            />

            <FeatureCard
              icon={<Users className="h-7 w-7" />}
              title="Organization collaboration"
              description="Create organization workspaces, invite members via email, and collaborate securely on shared documents within a centralized dashboard."
            />

            <FeatureCard
              icon={<Download className="h-7 w-7" />}
              title="AI report export"
              description="Download professionally formatted PDF reports containing AI-generated summaries, sentiment analysis, and extracted keywords for easy sharing."
            />

            <FeatureCard
              icon={<ShieldCheck className="h-7 w-7" />}
              title="Secure document management"
              description="Built with Clerk authentication, protected routes, and organization-based access, ensuring documents remain private and accessible only to authorized members."
            />
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-20">
        <div className="container max-w-5xl mx-auto px-6">
          <h2 className="text-3xl font-bold mb-12 text-center">How it works</h2>

          <div className="space-y-8">
            <Step
              n={1}
              title="Create or join an organization"
              description="Sign up, then create a workspace or accept an invitation to join one."
            />
            <Step
              n={2}
              title="Invite your team"
              description="Invite teammates by email. Only organization members can upload, analyze, or view its documents."
            />
            <Step
              n={3}
              title="Upload a document"
              description="Add a PDF, DOCX, TXT, or Markdown file. DocDocGo stores it in Vercel Blob Storage and extracts its text automatically."
            />
            <Step
              n={4}
              title="Run AI analysis"
              description="Generate a summary, sentiment, keywords, and answers to your questions using Gemini AI."
            />
            <Step
              n={5}
              title="Download or share"
              description="Export the original file or a formatted AI report as a PDF. Upload the same file again later, and DocDocGo keeps it as a new version."
            />
          </div>
        </div>
      </section>

      {/* Trust / stack strip */}
      <section className="border-t border-b py-14 bg-muted/20">
        <div className="container max-w-5xl mx-auto px-6">
          <p className="text-center text-sm text-muted-foreground mb-6">
            Built on a secure, modern stack
          </p>
          <div className="flex flex-wrap justify-center gap-x-10 gap-y-3 text-sm font-mono text-muted-foreground">
            <span>Next.js + TypeScript</span>
            <span>Clerk Authentication</span>
            <span>PostgreSQL + Prisma</span>
            <span>Vercel Blob Storage</span>
            <span>Gemini AI</span>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20">
        <div className="container max-w-4xl mx-auto px-6 text-center">
          <FileStack className={`h-10 w-10 mx-auto mb-4 ${ACCENT}`} />
          <h2 className="text-3xl font-bold">Ready to get started?</h2>
          <p className="mt-4 text-muted-foreground">
            Upload your first document and let AI do the reading.
          </p>

          <div className="mt-8">
            {userId ? (
              <Link href={primaryHref}>
                <Button size="lg">{primaryLabel}</Button>
              </Link>
            ) : (
              <Link href="/sign-up">
                <Button size="lg">
                  Create Account
                  <Sparkles className="ml-2 h-4 w-4" />
                </Button>
              </Link>
            )}
          </div>
        </div>
      </section>
    </main>
  );
}

function FeatureCard({
  icon,
  title,
  description,
}: {
  icon: React.ReactNode;
  title: string;
  description: string;
}) {
  return (
    <div className="rounded-xl border bg-background p-6">
      <div className={`inline-flex items-center justify-center h-11 w-11 rounded-lg mb-4 ${ACCENT_BG} ${ACCENT}`}>
        {icon}
      </div>
      <h3 className="font-semibold text-xl mb-2">{title}</h3>
      <p className="text-muted-foreground">{description}</p>
    </div>
  );
}

function Step({ n, title, description }: { n: number; title: string; description: string }) {
  return (
    <div className="flex gap-6">
      <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary text-primary-foreground font-semibold">
        {n}
      </div>
      <div>
        <h3 className="font-semibold text-lg">{title}</h3>
        <p className="text-muted-foreground">{description}</p>
      </div>
    </div>
  );
}